### ISSUE TITLE
Form Key Problem

### ISSUE THREAD

**Issue by ksaltik** [GordonLesti/Lesti_Fpc2#1]
a:5:{i:0;s:16:"Invalid form key";i:1;s:907:"#0 \app\code\core\Mage\Checkout\controllers\CartController.php(604): Mage::throwException('Invalid form ke...')
#1 app\code\core\Mage\Core\Controller\Varien\Action.php(418): Mage_Checkout_CartController->ajaxDeleteAction()
#2 \app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('ajaxDelete')
#3 \app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#4 \app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#5 \app\Mage.php(684): Mage_Core_Model_App->run(Array)
#6 \index.php(83): Mage::run('', 'store')
#7 {main}";s:3:"url";s:72:"/checkout/cart/ajaxDelete/id/2582/uenc/aHR0cDovL29uZXlldGljYXJldC5jb20v/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

When I disable all cache in magento 1.9.0.2 rwd design. The home pagebasket remains unupdated. Don't let me to delete its content.

Does Lesti_Fpc v.1 support form key?

**Comment by GordonLesti** [comment]
I'm sorry, Lesti_Fpc2 is not ready for production and maybe this repo will be deleted in the next weeks. Lesti_Fpc v.1 can handle form keys.
